# Generated by Django 5.1.15 on 2026-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('REJECTED', 'Recusado'), ('ENDED', 'Encerrado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_partnerships', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_income_totals', models.BooleanField(default=True)),
                ('share_income_details', models.BooleanField(default=True)),
                ('share_expense_totals', models.BooleanField(default=True)),
                ('share_expense_details', models.BooleanField(default=True)),
                ('share_client_names', models.BooleanField(default=False)),
                ('share_goals', models.BooleanField(default=True)),
                ('share_debts', models.BooleanField(default=True)),
                ('share_accounts', models.BooleanField(default=False)),
                ('partnership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='couples.partnership')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partnership',
            constraint=models.UniqueConstraint(fields=('creator', 'partner'), name='unique_partnership_pair'),
        ),
    ]
