# Generated by Django 5.1.15 on 2026-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta corrente'), ('SAVINGS', 'Poupança'), ('WALLET', 'Carteira'), ('DIGITAL', 'Conta digital'), ('INVESTMENT', 'Investimento'), ('CASH', 'Dinheiro')], max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10)),
                ('income_type', models.CharField(blank=True, choices=[('SALARY', 'Salário'), ('APPOINTMENT', 'Atendimento'), ('FREELANCE', 'Freelancer'), ('EXTRA', 'Receita extra'), ('INVESTMENT', 'Investimento'), ('REFUND', 'Reembolso'), ('SALE', 'Venda'), ('OTHER', 'Outros')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('competence_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Prevista'), ('PENDING', 'Pendente'), ('PARTIAL', 'Parcial'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('DEBIT_CARD', 'Cartão de débito'), ('CREDIT_CARD', 'Cartão de crédito'), ('BANK_TRANSFER', 'Transferência bancária'), ('BOLETO', 'Boleto'), ('OTHER', 'Outros')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='transactions.financialaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-settlement_date'],
            },
        ),
    ]
