# Generated by Django 5.1.15 on 2026-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_item_id', models.CharField(max_length=100, unique=True)),
                ('institution_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('UPDATING', 'Sincronizando'), ('UPDATED', 'Atualizado'), ('LOGIN_ERROR', 'Erro de login'), ('OUTDATED', 'Desatualizado'), ('ERROR', 'Erro')], default='UPDATING', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_account_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency_code', models.CharField(default='BRL', max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank_integration.bankconnection')),
                ('financial_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_sync', to='transactions.financialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_transaction_id', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Aguardando revisão'), ('CONFIRMED', 'Confirmada'), ('IGNORED', 'Ignorada')], default='PENDING_REVIEW', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resulting_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_from', to='transactions.transaction')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category')),
                ('synced_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='bank_integration.syncedaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
