# Generated by Django 5.1.15 on 2026-09-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('RECEIVABLE', 'A receber'), ('PAYABLE', 'A pagar')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('PARTIAL', 'Parcial'), ('PAID', 'Paga'), ('OVERDUE', 'Atrasada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
