# Generated by Django 5.1.15 on 2026-09-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('transactions', '0002_client_creditcard_creditcardpurchase_freelancedetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Opcional — alternativa a digitar person_name livremente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='transactions.client'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='person_name',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente quando `client` é usado.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('client__isnull', False), models.Q(('person_name', ''), _negated=True), _connector='OR'), name='debt_requires_client_or_person_name'),
        ),
    ]
