# Generated by Django 5.1.15 on 2026-09-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_client_alter_debt_person_name_and_more'),
        ('transactions', '0002_client_creditcard_creditcardpurchase_freelancedetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, help_text='Preenchido automaticamente quando `client` é usado.', max_length=150)),
                ('reason', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('RECEIVABLE', 'A receber'), ('PAYABLE', 'A pagar')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, help_text='Opcional — alternativa a digitar person_name livremente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_recurrence_rules', to='transactions.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_recurrence_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reason'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='debts.debtrecurrencerule'),
        ),
        migrations.AddConstraint(
            model_name='debtrecurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('client__isnull', False), models.Q(('person_name', ''), _negated=True), _connector='OR'), name='debt_recurrence_requires_client_or_person_name'),
        ),
    ]
